/**
 * Shell Identity Constants — Axolutions Visual System
 *
 * Every visual layer class is centralized here. Pages and layouts import from
 * this single file to guarantee consistency across the app.
 *
 * ALL constants include both light and dark: variants in a single string.
 * Pages never need `if (theme === "dark")` for Tailwind classes.
 *
 * The sidebar uses a fixed deep purple via `color-mix()` inline style regardless
 * of light/dark theme — import AXO_SIDEBAR_STYLE and apply directly.
 *
 * Layer model:
 *   Layer 0: <body>   — bg-background (token), overridden visually by the shell
 *   Layer 1: Shell    — AXO_SHELL_BG        (gradient background)
 *   Layer 2: Overlay  — AXO_SHELL_OVERLAY   (fixed subtle wash)
 *   Layer 3: Header   — AXO_HEADER_BAR      (glass header bar)
 *   Layer 4: Sidebar  — AXO_SIDEBAR_STYLE   (fixed deep purple, theme-invariant)
 *   Layer 5: Page     — AXO_PAGE_CONTAINER  (page content wrapper)
 *   Layer 6: Cards    — AXO_GLASS_CARD      (glass card)
 *
 * DO NOT edit this file per-project. It is generated by the axo-design-system
 * skill. Project-specific additions go in a separate file that re-exports these.
 */

import type { CSSProperties } from "react";

// ─── Layout Constants ────────────────────────────────────────────────────────

/** Layer 1: Outermost gradient background on <body> or shell wrapper */
export const AXO_SHELL_BG = [
  "bg-gradient-to-br",
  "from-purple-100/80 via-white to-indigo-100/80",
  "dark:from-purple-950/95 dark:via-gray-900 dark:to-indigo-950/95",
].join(" ");

/**
 * Layer 2a: Ambient glow — REQUIRED for the glass to read as glass.
 *
 * Without this, every card sits on a locally flat backdrop and `backdrop-blur`
 * has nothing to refract, so the whole system collapses into flat panels. The
 * radial blooms are defined as `.axo-shell-glow` in globals.css because
 * Tailwind cannot express layered radial gradients legibly.
 *
 * Render it as a fixed sibling directly after AXO_SHELL_BG.
 */
export const AXO_SHELL_GLOW = "axo-shell-glow fixed inset-0 pointer-events-none z-0";

/** Layer 2b: Fixed overlay wash, sits on top of the glow */
export const AXO_SHELL_OVERLAY = [
  "fixed inset-0 pointer-events-none z-0",
  "bg-gradient-to-br",
  "from-purple-300/10 via-transparent to-blue-300/10",
  "dark:from-purple-500/5 dark:via-transparent dark:to-blue-500/5",
].join(" ");

/** Layer 3: Top navigation / header bar */
export const AXO_HEADER_BAR = [
  "relative z-10 border-b backdrop-blur-xl",
  "bg-white/60 border-purple-200/40",
  "dark:bg-black/30 dark:border-white/10",
].join(" ");

/** Layer 5: Page content container (semi-transparent glass) */
export const AXO_PAGE_CONTAINER = [
  "relative rounded-3xl border backdrop-blur-sm",
  "bg-white/40 border-purple-200/20",
  "dark:bg-black/20 dark:border-white/10",
].join(" ");

/**
 * Layer 6: Standard glass card.
 *
 * The `inset 0 1px 0` top highlight is what sells the glass — it reads as light
 * catching the top edge of a pane. Without it the card is just a tinted box.
 */
export const AXO_GLASS_CARD = [
  "relative overflow-hidden rounded-3xl border backdrop-blur-xl",
  "bg-white/60 border-purple-200/30",
  "shadow-[0_4px_24px_-4px_rgba(147,51,234,0.10),inset_0_1px_0_rgba(255,255,255,0.60)]",
  "dark:bg-black/40 dark:border-white/15",
  "dark:shadow-[0_8px_32px_-8px_rgba(0,0,0,0.60),inset_0_1px_0_rgba(255,255,255,0.07)]",
].join(" ");

/** Inner gradient glow overlay for glass cards */
export const AXO_CARD_OVERLAY = [
  "absolute inset-0 rounded-3xl pointer-events-none",
  "bg-gradient-to-br",
  "from-purple-200/10 via-transparent to-blue-200/10",
  "dark:from-purple-500/5 dark:via-transparent dark:to-blue-500/5",
].join(" ");

// ─── Text Constants ──────────────────────────────────────────────────────────

/** Primary text — headings, main content */
export const AXO_TEXT_PRIMARY = "text-gray-900 dark:text-white";

/** Secondary text — subtitles, labels */
export const AXO_TEXT_SECONDARY = "text-gray-700 dark:text-white/90";

/** Muted text — descriptions, captions */
export const AXO_TEXT_MUTED = "text-gray-500 dark:text-white/60";

/** Subtle text — timestamps, hints */
export const AXO_TEXT_SUBTLE = "text-gray-400 dark:text-white/40";

/** Inline link */
export const AXO_LINK = [
  "underline underline-offset-4 transition-colors",
  "text-purple-700 hover:text-purple-900",
  "dark:text-purple-300 dark:hover:text-purple-200",
].join(" ");

// ─── Component Constants ─────────────────────────────────────────────────────

/** Inner dividers inside cards or sections */
export const AXO_BORDER = "border-purple-200/30 dark:border-white/10";

/** Glass input field */
export const AXO_INPUT = [
  "rounded-xl border backdrop-blur-sm",
  "bg-purple-50/50 border-purple-200/30 text-gray-900 placeholder-gray-400",
  "dark:bg-white/5 dark:border-white/10 dark:text-white dark:placeholder-white/40",
  "focus:outline-none focus:ring-2 focus:ring-purple-500/30 dark:focus:ring-purple-400/30",
  "focus:border-purple-400 dark:focus:border-purple-400/50",
].join(" ");

/** Disabled input field */
export const AXO_INPUT_DISABLED = [
  "rounded-xl border cursor-not-allowed",
  "bg-gray-100 border-gray-200 text-gray-400",
  "dark:bg-white/[0.02] dark:border-white/5 dark:text-white/30",
].join(" ");

/** Primary action button (purple accent, always white text) */
export const AXO_BUTTON_PRIMARY = [
  "rounded-xl font-medium transition-all",
  "bg-purple-600 text-white border border-purple-600",
  "hover:bg-purple-700 hover:border-purple-700",
  "dark:bg-purple-600 dark:border-purple-500/50",
  "dark:hover:bg-purple-500 dark:hover:border-purple-400/50",
].join(" ");

/** Secondary / ghost button */
export const AXO_BUTTON_SECONDARY = [
  "rounded-xl font-medium transition-all",
  "bg-purple-50/50 text-gray-700 border border-purple-200/30",
  "hover:bg-purple-100/60 hover:text-gray-900",
  "dark:bg-white/5 dark:text-white/70 dark:border-white/10",
  "dark:hover:bg-white/10 dark:hover:text-white",
].join(" ");

/** Outline button */
export const AXO_BUTTON_OUTLINE = [
  "rounded-xl font-medium transition-all",
  "bg-transparent text-gray-600 border border-purple-200/40",
  "hover:bg-purple-50/50 hover:text-gray-900 hover:border-purple-300/50",
  "dark:text-white/60 dark:border-white/15",
  "dark:hover:bg-white/5 dark:hover:text-white dark:hover:border-white/25",
].join(" ");

/** Destructive button */
export const AXO_BUTTON_DESTRUCTIVE = [
  "rounded-xl font-medium transition-all",
  "bg-red-600 text-white border border-red-600",
  "hover:bg-red-700 hover:border-red-700",
  "dark:bg-red-600/90 dark:border-red-500/50 dark:hover:bg-red-500",
].join(" ");

/** Feature / benefit row inside cards */
export const AXO_FEATURE_ROW = [
  "flex items-center gap-3 p-3 rounded-xl transition-colors",
  "hover:bg-purple-50/50",
  "dark:hover:bg-white/5",
].join(" ");

/** Small icon container (32x32 or 36x36) */
export const AXO_ICON_BOX = [
  "flex items-center justify-center rounded-xl",
  "bg-purple-100/60 text-purple-600",
  "dark:bg-purple-500/10 dark:text-purple-400",
].join(" ");

/** Badge / pill */
export const AXO_BADGE = [
  "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
  "bg-purple-100/60 text-purple-700 border border-purple-200/40",
  "dark:bg-purple-500/10 dark:text-purple-300 dark:border-purple-400/20",
].join(" ");

/** Modal dialog content */
export const AXO_MODAL = [
  "rounded-3xl border backdrop-blur-2xl",
  "bg-white/80 border-purple-200/40",
  "shadow-[0_24px_80px_-12px_rgba(147,51,234,0.15)]",
  "dark:bg-gray-900/90 dark:border-white/15",
  "dark:shadow-[0_24px_80px_-12px_rgba(0,0,0,0.6)]",
].join(" ");

/**
 * Sidebar nav links — theme-INVARIANT, like the sidebar they sit on.
 *
 * These deliberately carry no `dark:` variants. The sidebar is always the same
 * deep purple (AXO_SIDEBAR_STYLE), so a light-mode variant here would paint
 * dark purple text onto a dark purple panel and vanish. Everything rendered
 * inside the sidebar is styled against purple, never against the page theme.
 */
export const AXO_SIDEBAR_LINK_ACTIVE = [
  "flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all",
  "bg-white/15 text-white shadow-sm ring-1 ring-white/10",
].join(" ");

/** Inactive sidebar navigation link */
export const AXO_SIDEBAR_LINK_INACTIVE = [
  "flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all",
  "text-white/65 hover:text-white hover:bg-white/10",
].join(" ");

// ─── Sidebar Inline Styles (color-mix) ───────────────────────────────────────

/**
 * Sidebar background — fixed deep purple, same in light AND dark mode.
 *
 * A vertical gradient, not a flat fill: a full-height slab of one saturated
 * purple reads cheap and fights the rest of the shell. The `backgroundColor`
 * is the fallback for when the token is unavailable; the gradient paints over
 * it. Uses color-mix() because Tailwind cannot express these values.
 */
export const AXO_SIDEBAR_STYLE: CSSProperties = {
  backgroundColor: "color-mix(in srgb, oklch(0.45 0.25 290) 85%, black)",
  backgroundImage: "var(--axo-sidebar-gradient)",
};

/** Sidebar right edge — separates it from the shell without a hard line */
export const AXO_SIDEBAR_EDGE = "border-r border-white/10";

/** Sidebar brand/header block */
export const AXO_SIDEBAR_HEADER = "flex items-center gap-2.5 px-3 py-4 text-white";

/** Uppercase group label between sidebar sections */
export const AXO_SIDEBAR_SECTION_LABEL =
  "px-3 pt-5 pb-2 text-[10px] font-semibold uppercase tracking-widest text-white/35";

/** Divider inside the sidebar */
export const AXO_SIDEBAR_DIVIDER = "my-2 h-px bg-white/10";

/** Sidebar footer region (user, theme toggle, sign out) */
export const AXO_SIDEBAR_FOOTER = "mt-auto flex flex-col gap-1 border-t border-white/10 pt-3";

/** @deprecated Use AXO_SIDEBAR_STYLE instead */
export const AXO_SIDEBAR_STYLE_DARK = AXO_SIDEBAR_STYLE;

/** @deprecated Use AXO_SIDEBAR_STYLE instead */
export const AXO_SIDEBAR_STYLE_LIGHT = AXO_SIDEBAR_STYLE;

// ─── Extended Set ────────────────────────────────────────────────────────────
// Derived from the same rules as the core constants above. Use these instead of
// inventing one-off class strings in components.

/** Status badges — same shape as AXO_BADGE, semantic hues */
export const AXO_BADGE_SUCCESS = [
  "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
  "bg-emerald-100/60 text-emerald-700 border border-emerald-200/40",
  "dark:bg-emerald-500/10 dark:text-emerald-300 dark:border-emerald-400/20",
].join(" ");

export const AXO_BADGE_WARNING = [
  "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
  "bg-amber-100/60 text-amber-700 border border-amber-200/40",
  "dark:bg-amber-500/10 dark:text-amber-300 dark:border-amber-400/20",
].join(" ");

export const AXO_BADGE_DANGER = [
  "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
  "bg-red-100/60 text-red-700 border border-red-200/40",
  "dark:bg-red-500/10 dark:text-red-300 dark:border-red-400/20",
].join(" ");

/** Horizontal divider inside cards */
export const AXO_DIVIDER = "h-px w-full bg-purple-200/30 dark:bg-white/10";

/** Focus ring — apply to any custom interactive element */
export const AXO_FOCUS_RING = [
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
  "focus-visible:ring-purple-500/50 focus-visible:ring-offset-white",
  "dark:focus-visible:ring-purple-400/50 dark:focus-visible:ring-offset-gray-900",
].join(" ");

/** Loading skeleton block */
export const AXO_SKELETON = [
  "animate-pulse rounded-xl",
  "bg-purple-200/40",
  "dark:bg-white/10",
].join(" ");

/** Table header row */
export const AXO_TABLE_HEADER = [
  "text-left text-xs font-medium uppercase tracking-wide border-b",
  "text-gray-500 border-purple-200/30",
  "dark:text-white/50 dark:border-white/10",
].join(" ");

/** Table body row */
export const AXO_TABLE_ROW = [
  "border-b transition-colors",
  "border-purple-200/20 hover:bg-purple-50/50",
  "dark:border-white/5 dark:hover:bg-white/5",
].join(" ");

/** Empty state container */
export const AXO_EMPTY_STATE = [
  "flex flex-col items-center justify-center gap-3 rounded-3xl border border-dashed p-10 text-center",
  "border-purple-200/40 text-gray-500",
  "dark:border-white/10 dark:text-white/50",
].join(" ");

/** Tooltip surface */
export const AXO_TOOLTIP = [
  "rounded-xl border px-3 py-1.5 text-xs backdrop-blur-xl",
  "bg-white/90 border-purple-200/40 text-gray-900",
  "dark:bg-gray-900/90 dark:border-white/15 dark:text-white",
].join(" ");
